id = "misc-sanity-check"
name = "Sanity Check"
author = ".;,;."
description = "Here we go again. Time flies by doesn't it? .;,;.{it_seems_you_started_this_ctf_'sane'._Lets_see_if_you_can_end_it_as_sane_as_you_started.}"
category = "misc"
points.min = 10
points.max = 500

[flag]
file = "src/flag.txt"