id = "rev-liquid-glass"
name = "liqUID glASS"
author = "Sahuang"
description = """At WWDC 2025, Apple’s Human Interface “revolutionized” iOS with Liquid Glass—an effect, characterized by its fluid, jelly-like appearance, that adds a layer of interactivity to UI elements.


Here is my re-creation of liqUID glASS on Web and I applied it to the flag. Can you find it out?


<a target="_blank" href="https://liquid-glass.surge.sh/">https://liquid-glass.surge.sh/</a>

<img src="https://i.ibb.co/b5x1XqDr/ass.png" alt="Old Liquid Glass Youtube Thumbnail" style="width: 50%; height: auto;" />"""
category = "rev"
points.min = 50
points.max = 500

[flag]
file = "src/flag.txt"

[[provide]]
dir = "dist/"
as = "liquid-glass"
