id = "crypto-sums"
name = "sums"
author = "snow"
description = "I have a funny game, unfortunately the odds of you winning are basically 0, but I'm bored, so play with me and I'll give you a flag if you win."
category = "crypto"
points.min = 50
points.max = 500

[flag]
file = "chall/flag.txt"

[container.default]
build = "chall/"
privileged = true

[container.default.expose]
5000 = "tcp"

[[provide]]
dir = "dist/"
as = "sums"
