id = "misc-ti-1984"
name = "TI-1984"
author = "snow"
description = "Seems Stev the Intern made a... mistake in my last server. No matter! Now it's surely unescapable!"
category = "misc"
points.min = 50
points.max = 500
build_group = "windows"
strategy = "instanced"
host = "windows"

[flag]
file = "chall/flag.txt"

[container.default]
build = "chall/"

[container.default.expose]
80 = "http"

[[provide]]
dir = "dist/"
as = "ti-1984"
