id = "misc-sky"
name = "sky"
author = "smashmaster"
description = "look at the sky, what do you see? a bird? a plane? no, its a challenge about the sky! (autocomplete wrote everything after the first 4 words)"
category = "misc"
points.min = 50
points.max = 500

[flag]
file = "chall/flag.txt"

[container.default]
build = "chall/"
privileged = true

[container.default.expose]
5000 = "tcp"

[[provide]]
dir = "dist/"
as = "sky"
