id = "crypto-spontaneous"
name = "spontaneous"
author = "snow"
description = "I'm so random!"
category = "crypto"
points.min = 50
points.max = 500

[flag]
file = "chall/flag.txt"

[container.default]
build = "chall/"
privileged = true

[container.default.expose]
5000 = "tcp"

[[provide]]
dir = "dist/"
as = "spontaneous"
