version: "3.3"
services:
  geth:
    build: .
    container_name: ethereum
    environment:
      - DEPLOYER_PRIVATE_KEY=35d7e3183bbe3e89907724a7c50a1e3f7207af30d169812534558f3591e27b30
      - BLOCK_TIME=5
      - CHAIN_ID=31337
    ports:
      - 8545:8545
    restart: "no"

networks:
  default:
